remote_theme: "mmistakes/minimal-mistakes@4.17.2"
minimal_mistakes_skin: dark

locale: "pt-BR"
title: Ideias do Nada
email: bruno@bmarques.net
description: Blog pessoal.
url: "https://bmarques.net"
repository: "ElSaico/blog"
twitter_username: DataMarques
facebook_username: bm2290
search: true

permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone: "Europe/Lisbon"

author:
  name: "Bruno Marques"
  bio: "A lei que me governa é a primeira lei de Newton."
  location: "TBD, Portugal"
  email: "bruno@bmarques.net"
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/DataMarques"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://facebook.com/bm2290"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ElSaico"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/DataMarques"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://facebook.com/bm2290"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ElSaico"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      share: true
      related: true

plugins:
  - jekyll-paginate
  - jekyll-include-cache
  - jekyll-remote-theme
