title: Bruno Marques
email: bruno@bmarques.net
description: Blog pessoal.
baseurl: ""
url: "https://bmarques.net"
twitter:
  username: DataMarques

remote_theme: "mmistakes/minimal-mistakes@4.17.2"
plugins:
  - jekyll-admin
  - jekyll-include-cache
