remote_theme: "mmistakes/minimal-mistakes@4.17.2"
minimal_mistakes_skin: default

locale: pt-BR
title: Bruno Marques
email: bruno@bmarques.net
description: Blog pessoal.
baseurl: ""
url: "https://bmarques.net"
repository: "ElSaico/elsaico.github.io"

twitter:
  username: DataMarques
facebook:
  username: bm2290
author:
  #name: "Bruno Marques"
  bio: "The only law I always follow is Newton's third law."
  location: "TBD, Portugal"
  email: "bruno@bmarques.net"
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/DataMarques"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://facebook.com/bm2290"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ElSaico"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/DataMarques"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://facebook.com/bm2290"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ElSaico"

plugins:
  - jekyll-admin
  - jekyll-include-cache
  - jekyll-remote-theme

prose:
  rooturl: '_posts'
  siteurl: 'https://bmarques.net/'
  relativeLinks: 'https://bmarques.net/links.jsonp'
  media: 'media'
  ignore:
    - 404.html
    - index.html
    - _config.yml
    - /_layouts
    - /_includes
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "blog"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Apples"
              value: "apples"
            - name: "Bananas"
              value: "bananas"
    _posts/static:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""